name = "cfw-bun-hono-drizzle"
main = "src/index.ts"
compatibility_date = "2024-12-07"

[[d1_databases]]
binding = "DB"
database_name = "cfw-bun-hono-drizzle-d1"
database_id = "51c71e53-cb1d-4b6e-b0c8-a68b53d38279"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1